version: 2
jobs:
  build:
    docker:
      - image: bepsays/ci-hugo:latest
    steps:
      - checkout
      - run: git submodule update --init
      - run: 
          command: |
            hugo
            s3deploy -source=public/ -region=eu-west-1 -bucket=hugocdn.test -path=site1 
      - run: curl "https://cdn1.bep.is/__s3p/purge?expires=1507372365&sig=Dyj59gGcnFafFYMcat4HTjPWu1M%3D"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
