version: 2
jobs:
  build:
    docker:
      - image: bepsays/ci-hugo:latest
    steps:
      - checkout
      - run: git submodule update --init
      - run:
          command: |
            hugo
            s3pdeploy -source=public/ -region=eu-west-1 -bucket=hugocdn.test -path=site1
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
